development:
  adapter: postgresql
  encoding: latin1
  host: localhost
  database: parttrade_dev
  pool: 5
  timeout: 5000
  username: deploy
  password: "Avopav24_deploy"

production:
  adapter: postgresql
  encoding: latin1
  host: localhost
  database: parttrade
  pool: 5
  timeout: 5000
  username: deploy
  password: "Avopav24_deploy"
  
test:
  adapter: postgresql
  encoding: latin1
  host: localhost
  database: parttrade_tesdt
  pool: 5
  timeout: 5000
  username: deploy
  password: "Avopav24_deploy"