# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d2bf0ee23eb3eccc46ad0f508b4dfb978e30ea620041d31bd909bf8f123bab3dc8a6d5d38ebf360c48baebbb18b2c1a2d30a56b0c42a2ac10901011b88d6b03

test:
  secret_key_base: 3bec120b028c350eec1ad1ca16b0ee068e0db5ae991264443206ab78be8beebbaf2128aaf8bc95e622fad4ff74b8d398d04d4ed263bc241770d98d3ab48f4b95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: '1234567890'
